FEW_SHOT_CLASSIFICATION_AD = "AD"
FEW_SHOT_CLASSIFICATION_NOT_AD = "NOT_AD"

few_shot_AD_example_1 = '''It doesn’t matter whether you’re from IIT, NIT, or a Tier-3 college. What matters is how much you carry within yourself. The truth is, companies like Microsoft aren’t scanning for logos on your resume. They’re searching for something deeper: → Your ability to solve problems when nothing works. → Your consistency when things drag on for months. → Your execution when production is breaking at 2 a.m. and the pressure is unbearable. Here’s the hard truth - No one hires a degree. → They hire resilience. → They hire clarity under fire. → They hire the ability to keep your team stable, your customers reassured, and your environment intact. Especially when things get messy. Because your job isn’t just about finishing tasks. It’s about creating balance, earning trust, and proving that you can handle the storms, not just the sunshine. And storms do come. Customer escalations spiral, tempers rise, and sometimes even you feel stuck. In those moments, what saves you isn’t theory. It’s how you balance, communicate, and lead from wherever you stand. This Saturday, 20th September at 5:00 PM, two Senior SDEs from Microsoft Rishi Prakash and Abinay Bingumalla are opening the curtain for a free, no-fluff masterclass: “What does it take to become a Microsoft SDE?” This is your golden chance to register : https://shorturl.at/c0c5B They’ll walk you through the mindset, the insider nuances, and the unspoken expectations that actually define growth inside a company like Microsoft. Step into September with clarity, direction, and an edge that most candidates never get.'''
few_shot_AD_example_2 = '''Before sitting for DSA rounds in senior-level interviews, Here’s what I learnt from my interview experiences👇 The count of LeetCode problems does NOT get you through rounds at top product companies. It’s how well you solve the correct ones under pressure. That’s why I’m sharing this “100 Most Liked LeetCode Problems” doc with you all. Big thanks to Bosscoder Academy for putting this together 🙌 🔗 Check them out here → https://bit.ly/41We1oh What makes this list stand out 📄 ✔️ Community-favourite problems, vetted by experienced engineers ✔️ Coverage of key patterns: Arrays, Strings, Linked Lists, Trees, Graphs, DP, Sliding Window & more ✔️ Balanced mix of Easy/Medium/Hard: designed for real interview value ✔️ Helps you build clarity & speed without burning time on low-signal grind It’s a focused set of high-signal questions that actually move the needle in interviews. If you’re an experienced SDE with rusty DSA or preparing for senior roles at PBCs, I’d recommend exploring the programs built by Rajat Garg & his team. They’ve helped 2200+ engineers switch to top product companies, maybe you’re next? 🚀'''
few_shot_AD_example_3 = '''20+ rejections. Countless screenings. A lot of “We’ll get back to you.” If I gave those interviews again today, I KNOW I would walk out with an offer. Not because I suddenly got lucky. But because I finally learned the value of structure over hustle. Here’s what made the difference 👇 🔹 Focus on ONE language Not just syntax, but concepts, edge cases, and trade-offs that actually matter in interviews. 🔹 Build problem-solving patterns Arrays, Strings, Trees, Graphs, DP… once I recognized the patterns, new questions felt familiar. 🔹 Strong CS fundamentals OS, DBMS, CN, interviewers dig into the “why” behind your answers, not just the “what.” 🔹 Mocks? GAMECHANGER It wasn’t just about solving problems, it was about communicating under pressure. Mock interviews exposed my blind spots and gave me confidence. That’s what helped me eventually land at ServiceNow after years of trial, error, and persistence. And if you’re a working SDE aiming to make your next big switch, you don’t need to figure it out alone. That’s where Bosscoder Academy comes in. 🔗 Explore their programs here: https://bit.ly/4pww1zw They’ve already helped 2200+ engineers crack top product-based roles with structured prep in DSA, System Design, and Full Stack, along with 1:1 mentorship, mock interviews, and complete job switch support. hashtag#collab hashtag#servicenow hashtag#sdeprep hashtag#career hashtag#growth hashtag#tech hashtag#pbc hashtag#jobswitch'''
few_shot_AD_example_4 = '''I tried over 40 variations. Most didn’t get opened. A few did. And those few got me interviews at Zomato, Traya & more. This post is only about that first battle. Getting your email opened. → What makes a founder click → The subject line that worked on top founders → A few that backfired (badly) → And the exact thought process I now use while writing subject lines Drop your email in the comments, I’ll send you my full list of subject lines that worked for me.'''
few_shot_AD_example_5 = '''HIRING! HIRING! HIRING! !!WE ARE HIRING FOR WORK FROM HOME!! VACANCIES ARE AVAILABLE FOR FRESHERS, COLLEGE STUDENTS / HOUSEWIVES & INTERNS 2025. We are hiring for full-time/part-time entry-level & remote jobs Income-20k to 60k per month + incentives Location- work from home Qualification - any graduation Working - 9 pm to 6 pm, weekends off Open Positions: HR Executive, Team Management, Social Media Optimization available hashtag#Comment hashtag#interested below We'll personally review your profile for the perfect match and shortlist you within 24 hours. Like the post and follow for more hiring update Send your Resume to my WhatsApp number +91 7027084535(Swati)'''

few_shot_NOT_AD_example_1 = '''Tired of "𝗦𝘂𝗴𝗴𝗲𝘀𝘁𝗲𝗱" and "𝗣𝗿𝗼𝗺𝗼𝘁𝗲𝗱" posts cluttering your LinkedIn feed? I built a Chrome Extension to remove the noise and give you a cleaner LinkedIn experience. Best part, it is hashtag#free and hashtag#opensource! Introducing 𝗡𝗼𝗡𝗼𝗶𝘀𝗲 𝗟𝗶𝗻𝗸𝗲𝗱𝗜𝗻! 🛠 Get it now: 👉 Chrome Web Store: https://lnkd.in/gtkyHRbw 👉 GitHub (manual install): https://lnkd.in/gNbi3ePk 💻 Works on: Chrome, Brave, Edge, Vivaldi, Opera (any Chromium-based browser). 🦊 Firefox support coming soon! Plus, I’ll be adding more features to further cleanse your LinkedIn experience. Feedback and contributions are welcome! Also, check out my logo design skills 😄 hashtag#LinkedIn hashtag#ChromeExtension hashtag#OpenSource'''
few_shot_NOT_AD_example_2 = '''Excited to announce the publication of our paper, "Proof-of-Trust-in-Expertise (PoTE): A Consensus Mechanism for Healthcare Consortium Blockchains"! Huge shoutout to my co-authors and super close friends Akhilesh Kasturi and Sonaakshi K for their hard work. A big thank you to Dr. Beena B.M. ma'am for her invaluable guidance and support throughout the entire process. This is a field that I am absolutely bullish on and genuinely feel can make the world a more transparent and fairer place for everyone. Also shoutout to Peeta Basa Pati sir who graded our Phase-1 project which was based on this topic and gave valuable insights to me about coding practices that I still remember. He told me to always document the limitations and failed test cases when developing something (There were unexpected errors during the final demo... 😂😅) Paper Link: https://lnkd.in/eJ4bAzem Source Code: https://lnkd.in/gaxPYU_P hashtag#Research hashtag#Blockchain hashtag#Healthcare'''
few_shot_NOT_AD_example_3 = '''Education as a field of work is of less interest to the business community. However, brilliant researchers like Rohit strive to innovate and make education easily available for all. Rohit has been striving to apply AI to make education easily available to masses. He also strives to employ narrative based learning to explain complex concepts for easy comprehension. With such efforts, humanity moves to next level of evolution and this world becomes a better place to live in.'''
few_shot_NOT_AD_example_4 = '''Ambani can hire best Managers and give them freehand to run and/or expand the business! Politician can trust the IAS officers and let them frame major policy decisions. If you are a sportsman and how ever rich you are, you need to do it yourself. Kohli has to run to get a score on the score board ! As a sportsman, one must deliver themselves. No outsourcing....no sub-delegation ! In our game of life, lets be the sportspersons and excel in what we do. Enjoy doing it ! Do not worry about the form and injuries. They are part of the game. Just believe in yourself . The pitch is yours !'''
few_shot_NOT_AD_example_5 = '''Hello Connections, Lately, I’ve noticed a rise in job posts asking candidates to comment “Interested”, send CVs to random emails, or even share details over WhatsApp. Unfortunately, most never receive even a basic acknowledgment. What’s more worrying is that many of these posts aren’t genuine opportunities at all. Some are created just to boost engagement or gain followers, leaving sincere job seekers waiting in hope—and ultimately disappointed. Every resume sent is not just a document; it represents someone’s effort, career aspirations, and personal responsibilities. The least we can do as HR professionals is to acknowledge those applications. Even a short response can make a big difference. Let’s build a recruitment culture that’s authentic, transparent, and respectful. Because behind every application is a real story and a real person. 💙 hashtag#Recruitment hashtag#Hiring hashtag#RespectForCandidates hashtag#FakeRecruitment hashtag#HumanResource hashtag#HR'''



SAMPLE_1 = '''A desire to solve the world's problems with technology inspired the choice of career for Aparna Ganesh Kanade, Lead Business Analyst at Chubb India. In her role, she enjoys pushing the boundaries of what is possible with ever-evolving technology. She credits her family's support for her success. Her advice to aspiring technologists is to make the most of every available opportunity and let their work define their image. Explore opportunities at Chubb's Engineering Center in India: https://bit.ly/4jsS4UN hashtag#WomenAtChubb hashtag#ChubbIndia'''
SAMPLE_2 = '''I don’t even know who this guy is—no clue what sins I committed or what past-life revenge he’s taking 🤦‍♂️. In a 30-minute YouTube tutorial, he pops up at least 60 times… 🤥🤥🤥 Because of him, I even stopped eating ₹10 chips 😆😜 (they’re just filled with air anyway). Dear YouTube, please put an end to his game once and for all… 😆'''
SAMPLE_3 = '''💡Change brings challenges — and opportunities 💡 This is my very first post on LinkedIn, and it comes at a time of transition. Like many others, I was recently impacted by the mass layoffs at Oracle. While it’s never easy to say goodbye, I’m grateful for the journey, the brilliant colleagues I’ve learned from, and the challenging projects that helped me grow both technically and personally. Over the past 3+ years, I’ve gained hands-on experience across: 🔹 Machine Learning & MLOps — building and optimizing models, streamlining workflows, and improving automation. 🔹 Distributed Systems & Backend Development — designing scalable, secure, and efficient services. 🔹 Cloud & Modern Software Practices — leveraging containerization, microservices, and CI/CD to deliver impactful solutions. These experiences have strengthened my ability to tackle complex problems and contribute effectively in fast-paced, innovation-driven environments. 🔗 Let’s connect: https://lnkd.in/gH-SwFWY I’d truly appreciate your support — whether it’s advice, referrals, or just a quick connection. Here’s to turning this transition into an exciting new chapter! 🚀 hashtag#OpenToWork hashtag#SoftwareEngineering hashtag#DistributedSystems hashtag#MachineLearning hashtag#MLOps hashtag#TechCareers hashtag#Networking'''
SAMPLE_4 = '''If you’re in Pune, check out the API Conf Pune 2025 conference tomorrow, WeMakeDevs is proud to be a sponsor! It’s a community-driven, one-day conference bringing together 500+ developers, architects, and tech leaders to explore the future of APIs. Register: https://www.theapiconf.com'''


# Few-shot prompt to improve reliability of AD vs NOT_AD classification
def fewShotPrompt(inputData):
    return (
        "You are a strict Binary classifier. Decide if the given LinkedIn post is an advertisement.\n"
        f"Output exactly One token with no punctuation, no explanation, and no extra text: {FEW_SHOT_CLASSIFICATION_AD} or {FEW_SHOT_CLASSIFICATION_NOT_AD}.\n"
        "---\n"
        "Examples:\n"
        f"Text: {few_shot_AD_example_1}\n"
        f"Label: {FEW_SHOT_CLASSIFICATION_AD}\n"
        "---\n"
        f"Text: {few_shot_NOT_AD_example_2}\n"
        f"Label: {FEW_SHOT_CLASSIFICATION_NOT_AD}\n"
        "---\n"
        f"Text: {few_shot_AD_example_3}\n"
        f"Label: {FEW_SHOT_CLASSIFICATION_AD}\n"
        "---\n"
        f"Text: {few_shot_NOT_AD_example_4}\n"
        f"Label: {FEW_SHOT_CLASSIFICATION_NOT_AD}\n"
        "---\n"
        f"Text: {few_shot_AD_example_5}\n"
        f"Label: {FEW_SHOT_CLASSIFICATION_AD}\n"
        "---\n"
        f"Text: {few_shot_NOT_AD_example_1}\n"
        f"Label: {FEW_SHOT_CLASSIFICATION_NOT_AD}\n"
        "---\n"
        f"Text: {few_shot_AD_example_2}\n"
        f"Label: {FEW_SHOT_CLASSIFICATION_AD}\n"
        "---\n"
        f"Text: {few_shot_NOT_AD_example_3}\n"
        f"Label: {FEW_SHOT_CLASSIFICATION_NOT_AD}\n"
        "---\n"
        f"Text: {few_shot_AD_example_4}\n"
        f"Label: {FEW_SHOT_CLASSIFICATION_AD}\n"
        "---\n"
        f"Text: {few_shot_NOT_AD_example_5}\n"
        f"Label: {FEW_SHOT_CLASSIFICATION_NOT_AD}\n"
        "---\n"
        f"Text: {inputData}\n"
        "Label:"
    )